file:
  parser:
    token:
      csv-separator: ;
      text: '{Q}'
      true-text: '{true}'
      false-text: '{false}'

test:
  questions:
    count: 5

path:
  question:
    file:
      ru: src/main/resources/questions_ru.csv
      en: src/main/resources/questions_en.csv

application:
  default:
    localization: en
#    localization: ru
  available:
    localizations: en ru